import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { ReactQueryClientProvider } from "@/components/Provider/ReactQueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryClientProvider>
      <ClerkProvider appearance={{
        variables: { colorPrimary: '#624cf5' }
      }}>
        
          <html lang="en">
            <body className="antialiased min-h-screen pt-16"
            >
              {children}
            </body>
          </html>
        
      </ClerkProvider>
    </ReactQueryClientProvider>
    );
}